### ISSUE TITLE
Please explain what 'NG' English language string means

### ISSUE THREAD

**Issue by germanvaleroelizondo** [justinhunt/moodle-mod_readaloud#11]
Hi,
When I was translating this plugin in AMOS into Mexican Spanish, I came upon this English language string:

3.6dev | ng | readaloud  'NG'

I am unable to translate 'NG' into Spanish, and I guess most Moodle AMOS translators would have difficulty in translating it into any other language different from English variations (US/K12).

Does 'NG' stand for 'No Good' ?

Can you please replace the name for this string with a more meaningful one.

Thanks in advance.

**Comment by justinhunt** [comment]
Thanks for the message. I will update it in the next release (pretty soon). But I will leave the key the same. It means: "No good" 
I have been badly infected by English that has become Japanese, and it is commonly used here.
 I will change English "NG" to "Not OK"

And thanks so much for doing this work for Read Aloud. I really appreciate that,

**Comment by justinhunt** [comment]
fixed a versions back
