### ISSUE TITLE
Source code and license of the Flash parts of the plugin

### ISSUE THREAD

**Issue by mudrd8mz** [justinhunt/moodle-mod_readaloud#3]
I can't see the source code for the `PoodllMP3Record.lzx.swf10.swf` included with the package. In fact, I quickly checked and this seems to be the case with other SWF files in other PoodLL plugins, too. I may be just missing something (sorry for that in advance) but the GPL is quite clear about this requirement and we are expected to check it. See https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing for reference.

Additionally, I found the `audio/justinsplainenglishlicense.txt` which again contradicts the conditions of the GPLv3, as far as I understand it.

**Comment by justinhunt** [comment]
Ouch. I have some work to do. Thanks for doing all the testing.

Right now, let me just answer to this one about licensing. Its GPL but the
source for the flash components of PoodLL and friends was not from the
beginning modular. More like monolithic. There were a lot of dependencies
and it was also tied up with the development platform (OpenLaszlo) so
initally I just said, I will supply the source if you need it. Later I made
the MP3 recorder into a self contained standalone project (not Moodle), and
distributed an audio recording SDK with sample projects, docs and examples
based on that. Thats where the plainenglishlicense that you found came
from. Its actually not required here. The upshot of all that is that the
source for the mp3 recorder can be added here, and the funny license can be
removed.

For PoodLL its still a bit problematic, but I will do something.

**Comment by mudrd8mz** [comment]
> I just said, I will supply the source if you need it

Thanks for the clarification Justin. This case is indeed valid according to the GNU GPLv3. I was not quite right telling that the source code must be included within the package. But there must be a clear info (ideally in a README file next to the SWF files) with the instructions of how the users can get the source codes (again, ideally if you just publish them on your site and users can download them). The sections 1. and 6. of the GPLv3 provide more details.

**Comment by justinhunt** [comment]
I added a link to the download for the source code in the README and removed the problem license.
